exchangeRateURL: https://v6.exchangerate-api.com/v6/f40ba9794464d382433580d9/latest/BYN

#spring:
#  datasource:
#    password: 72305
#    url: jdbc:mysql://localhost:3306/currency?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#    username: root
##  profiles:
##    active: local

server:
  port: 8083

#for deploy to docker
spring:
  datasource:
    password: password
    url: jdbc:mysql://mysql-container:3306/currencies
    username: root
  jpa:
    hibernate:
      ddl-auto: update

circuitBreakerId: currencyApiService